### ISSUE TITLE
Review Screen - Not (always) totaling hours

### ISSUE THREAD

**Issue by DC7D** [hammurabis-code/TimeManagement#1]
When viewing entries on the review or admin review screens, the total hours sometimes displays as "0". Could not determine a pattern. I would see a 0 hour total when reviewing a single entry, or hundreds.

**Comment by DC7D** [comment]
![hour calc](https://cloud.githubusercontent.com/assets/1590736/23288477/d220ec7c-fa11-11e6-9974-8a7572d0e3f1.png)

**Comment by hammurabis-code** [comment]
Resolved in latest merge #4
