### ISSUE TITLE
Daily hours over 24 allowed on edit

### ISSUE THREAD

**Issue by DC7D** [hammurabis-code/TimeManagement#2]
The app will allow you to add entries that go over 24 hours for the day if the entry already exists and you edit it to change the date.

I was testing the 24 hour rejection. I had two entries for November 1st that totaled 18 hours. I added a third entry that would have put it over but accidentally added it to October 31st. I went in and edited it to November 1st. It didn't throw a warning and allowed me to save it. I deleted that entry and added a new one for November 1st that put it over 24 hours for the day and the app rejected it as expected.

**Comment by hammurabis-code** [comment]
Resolved with latest merge #4
