### ISSUE TITLE
Code Preferences on the Profile Screen not displayed

### ISSUE THREAD

**Issue by DC7D** [hammurabis-code/TimeManagement#3]
Specific to the production environment, when you visit the code preferences on the profile screen, no boxes are checked. You can select codes by checking the boxes, clicking "Save Changes" and the new codes are available on the time entry screen, but when you navigate back to the profile screen, and open the code preferences, no boxes are checked indicating which codes are already selected.

**Comment by DC7D** [comment]
One user reported that selections made on the code preferences section of the profile screen were not reflected in the time entry dropdown of work codes. "Changes made to Work Code preferences on the PROFILE screen were saved (message appeared) yet on the ENTER TIME screen, the old Word Code preferences  were displayed."

**Comment by hammurabis-code** [comment]
It appears this function is showing the same issue on the test site. No errors are reported in the console either. 
Since this function was working previously a change must have broken either the bindings or the type.

**Comment by hammurabis-code** [comment]
Resolved with latest merge #4
